// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/primes.h"
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

// is_prime
std::vector<bool> is_prime(std::vector<int> x);
RcppExport SEXP _primes_is_prime(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<int> >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(is_prime(x));
    return rcpp_result_gen;
END_RCPP
}
// next_prime
Rcpp::IntegerVector next_prime(std::vector<int> x);
RcppExport SEXP _primes_next_prime(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<int> >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(next_prime(x));
    return rcpp_result_gen;
END_RCPP
}
// prev_prime
Rcpp::IntegerVector prev_prime(std::vector<int> x);
RcppExport SEXP _primes_prev_prime(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<int> >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(prev_prime(x));
    return rcpp_result_gen;
END_RCPP
}
// generate_primes_
std::vector<int> generate_primes_(int min, int max);
RcppExport SEXP _primes_generate_primes_(SEXP minSEXP, SEXP maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type min(minSEXP);
    Rcpp::traits::input_parameter< int >::type max(maxSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_primes_(min, max));
    return rcpp_result_gen;
END_RCPP
}

// validate (ensure exported C++ functions exist before calling them)
static int _primes_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP _primes_RcppExport_registerCCallable() { 
    R_RegisterCCallable("primes", "_primes_RcppExport_validate", (DL_FUNC)_primes_RcppExport_validate);
    return R_NilValue;
}

static const R_CallMethodDef CallEntries[] = {
    {"_primes_is_prime", (DL_FUNC) &_primes_is_prime, 1},
    {"_primes_next_prime", (DL_FUNC) &_primes_next_prime, 1},
    {"_primes_prev_prime", (DL_FUNC) &_primes_prev_prime, 1},
    {"_primes_generate_primes_", (DL_FUNC) &_primes_generate_primes_, 2},
    {"_primes_RcppExport_registerCCallable", (DL_FUNC) &_primes_RcppExport_registerCCallable, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_primes(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
